### ISSUE TITLE
GitHub action fails silently

### ISSUE THREAD

**Issue by tugrulates** [lirantal/is-website-vulnerable#101]
There is an edge case where the action will fail silently, and mark the job as succeeded.

The input `scan-url` for the action is required. However, the run can still fail if an empty string is passed during the run. In my case, I was passing the output of another job.

## Expected Behavior

Job failure.

## Current Behavior

Job passing with the following logs.

```
Run lirantal/is-website-vulnerable@master
Woops! You forgot to provide a URL of a website to scan.
25l? Please provide a URL to scan: ‣  25h
```

## Steps to Reproduce (for bugs)

```
  snyk:
    runs-on: ubuntu-latest
    steps:
        uses: lirantal/is-website-vulnerable@master
        with:
          scan-url: ${{ inputs.url }}
```
